governance/security.md

https://github.com/open-cluster-management/backlog/issues/551

Added RBAC tables

---

governance/policy_overview.md

https://github.com/open-cluster-management/backlog/issues/1441

Updates for creating a policy

---

cert_manager/cert_root_ca.md
governance/cert_policy_ctrl.md
governance/cis_policy_ctrl.md
governance/cis_policy_rules.md
governance/compliance_intro.md
governance/config_policy_ctrl.md
governance/create_policy.md
governance/iam_policy_ctrl.md
governance/policy_samples.md

Fixing anchors for the security section

---

about/architecture.md
about/gdpr_readiness.md
about/known_issues.md
cli/cli_mc_commands.md
cli/multicluster_cli.md
console/console.md
console/vwt_search.md

updating anchors

---

install/plan_capacity.md
install/supported_clouds.md
manage_applications/app_lifecycle.md
manage_applications/app_resources.md
manage_applications/deployment_app.md
manage_applications/deployment_rollout.md
manage_applications/managing_apps_console.md

Fixing anchors

---

manage_applications/managing_placement_rules.md

Please check the update and I highlighted an area to look at where we have Tiller as a value
Related to: https://github.com/open-cluster-management/backlog/issues/924
https://github.com/open-cluster-management/rhacm-docs/issues/254

#54 Update managing_placement_rules.md

---

manage_applications/managing_apps.md
manage_applications/managing_channels.md
manage_applications/managing_deployables.md
manage_applications/managing_placement_rules.md
manage_applications/managing_secrets.md
manage_applications/managing_subscriptions.md
manage_cluster/cloud_conn_aks.md

fixing more anchors

---

about/whats_new.md

small typo

---

install/install_connected.md

Removing some syntax

---

about/architecture.md
console/console.md
governance/compliance_intro.md

https://github.com/open-cluster-management/rhacm-docs/issues/358

[GRC] Removing details about the Overview page

---

install/install_connected.md
manage_cluster/import_cli.md
manage_cluster/import_gui.md
troubleshoot_acm/troubleshooting.md

https://github.com/open-cluster-management/backlog/issues/380

Updating kubectl version support

---

governance/security.md

removed the Operator column out of the table

---

governance/security.md

updating row RBAC table for console

---

governance/cert_policy_ctrl.md
governance/cis_policy_ctrl.md
governance/compliance_intro.md
governance/config_policy_ctrl.md
governance/manage_grc_policy.md
governance/policy_overview.md

https://github.com/open-cluster-management/rhacm-docs/issues/370

Access image vulnerability violation

---

governance/cis_policy_ctrl.md

no issue, noticed the link was broken

fixing inline link

---

about/architecture.md
about/components.md
about/gdpr_readiness.md
about/known_issues.md
about/notices.md
about/release_notes.md
about/welcome.md
about/whats_new.md
apis/api.md
cert_manager/byok_certs.md
cert_manager/cert_mgmt_ingress.md
cert_manager/cert_root_ca.md
cert_manager/certificates.md
cli/cli_mc_commands.md
cli/installing_mc_plugin.md
cli/multicluster_cli.md
console/cluster_label.md
console/console _access.md
console/console.md
console/vwt_search.md
governance/cis_policy_rules.md
governance/create_deploy.md
governance/create_policy.md
governance/iam_policy_ctrl.md
governance/manage_policy.md
governance/policy_controllers.md
governance/policy_example.md

https://github.com/open-cluster-management/rhacm-docs/issues/392

removing dates

---

manage_applications/managing_deployables.md
manage_applications/managing_placement_rules.md
manage_applications/managing_secrets.md
manage_applications/managing_subscriptions.md
manage_applications/migrate_subscriptions.md
manage_applications/overview.md
manage_cluster/add_cloud_providers.md
manage_cluster/cloud_conn.md
manage_cluster/cloud_conn_aks.md
manage_cluster/cloud_conn_aws.md
manage_cluster/cloud_conn_bare.md
manage_cluster/cloud_conn_gke.md
manage_cluster/create.md
manage_cluster/create_aks.md
manage_cluster/create_bare.md
manage_cluster/create_gke.md
manage_cluster/create_ocp_aws.md
manage_cluster/import.md
manage_cluster/import_gui.md
manage_cluster/intro.md
manage_cluster/modify_endpoint.md
manage_cluster/scale.md
manage_cluster/upgrade.md
services/serv_ingress.md
services/serv_istio.md
services/serv_kube.md
services/serv_overview.md
services/serv_prep.md
services/service_registry.md
services/working_serv_intro.md

https://github.com/open-cluster-management/rhacm-docs/issues/392

removing the last of the dates

---

governance/config_policy_ctrl.md
governance/policy_samples.md

https://github.com/open-cluster-management/backlog/issues/1745#issuecomment-615294432

Removing a policy sample

---

about/known_issues.md

https://github.com/open-cluster-management/backlog/issues/1726

adding known issue for search

---

console/console.md

https://github.com/open-cluster-management/backlog/issues/1726#issuecomment-616499731

Added a note on the search doc

---

about/known_issues.md
console/console _access.md
install/installation.md

* Refresh 4/13 conflicts (#374)
* Update README.md (#242)
* Update README.md
small change, still reviewing
* Update Search console topic (#244)
Co-authored-by: Jorge Padilla <jpadilla@redhat.com>
* small change, no issue
* small change, no issue (#245)
* remove section (#246)
* Notes from live meeting (#250)
* Live meeting update (#252)
* from live mtg (#251)
* Added RBAC tables (#255)
* Added RBAC tables 
https://github.com/open-cluster-management/backlog/issues/551
* Update security.md
updates
* small change, no issue (#256)
* Update README.md (#242) (#243)
* Update README.md (#242)
* Update README.md
small change, still reviewing
Co-authored-by: brandi swope <bswope@redhat.com>
Co-authored-by: Mikela Dockery …

Resync branches

---

about/known_issues.md
console/console _access.md
install/installation.md

* Refresh 4/13 conflicts (#374)
* Update README.md (#242)
* Update README.md
small change, still reviewing
* Update Search console topic (#244)
Co-authored-by: Jorge Padilla <jpadilla@redhat.com>
* small change, no issue
* small change, no issue (#245)
* remove section (#246)
* Notes from live meeting (#250)
* Live meeting update (#252)
* from live mtg (#251)
* Added RBAC tables (#255)
* Added RBAC tables 
https://github.com/open-cluster-management/backlog/issues/551
* Update security.md
updates
* small change, no issue (#256)
* Update README.md (#242) (#243)
* Update README.md (#242)
* Update README.md
small change, still reviewing
Co-authored-by: brandi swope <bswope@redhat.com>
Co-authored-by: Mikela Dockery …

Doc prod (#411)

---

governance/policy_example.md
governance/policy_overview.md

https://github.com/open-cluster-management/backlog/issues/1773

improved security control explaination

---

manage_applications/deployment_rollout.md

1. modify sample yamls.
2. remove unnecessary comment out lines 
3. misc updates

Modify sample yamls in the rolling update doc

---

manage_applications/managing_channels.md

https://github.com/open-cluster-management/backlog/issues/1663

Live dev review

---

console/console.md
governance/security.md
manage_cluster/cloud_conn.md
manage_cluster/cloud_conn_bare.md
manage_cluster/create_bare.md

https://github.com/open-cluster-management/backlog/issues/1720

Bare metal host adoption is not available, removing mentions of it

---

README.md

https://github.com/open-cluster-management/backlog/issues/1860

updating the known issues link in the README

---

governance/compliance_intro.md

https://github.com/open-cluster-management/backlog/issues/1436

adding note about the replicated policies

---

governance/config_policy_ctrl.md
governance/policy_samples.md

adding a enforce and inform table

---

manage_applications/managing_subscriptions.md

https://github.com/open-cluster-management/backlog/issues/1664

---

governance/cis_policy_ctrl.md

https://github.com/open-cluster-management/backlog/issues/1931

Removed non-OCP sample and added note

---

governance/cis_policy_ctrl.md

https://github.com/open-cluster-management/backlog/issues/1928

removing important note about the secret for cis enablement

---

release_notes/known_issues.md

 open-cluster-management/backlog#1738

---

install/uninstall.md

open-cluster-management/backlog#1997 Change title

---

governance/compliance_intro.md
governance/config_policy_ctrl.md
governance/policy_samples.md
summary.md

https://github.com/open-cluster-management/backlog/issues/1983

Clarifying the doc title for configuration sample policies

---

subscription_sample.md/app_ sample.md
subscription_sample.md/app_lifecycle.md
subscription_sample.md/app_management_overview.md
subscription_sample.md/app_resources.md
subscription_sample.md/channel_ sample.md
subscription_sample.md/create_apps.md
subscription_sample.md/deployable_ sample.md
subscription_sample.md/deployment_app.md
subscription_sample.md/deployment_rollout.md
subscription_sample.md/docinfo.xml
subscription_sample.md/managing_apps.md
subscription_sample.md/managing_apps_console.md
subscription_sample.md/managing_channels.md
subscription_sample.md/managing_deployables.md
subscription_sample.md/managing_placement_rules.md
subscription_sample.md/managing_secrets.md
subscription_sample.md/managing_subscriptions.md
subscription_sample.md/master.adoc
subscription_sample.md/migrate_subscriptions.md
subscription_sample.md/secret_ sample.md
subscription_sample.md/subscription_sample.md

Reverts open-cluster-management/rhacm-docs#495

Revert "open-cluster-management/backlog#1573-more samples, ghost folder remov…"

---

governance/cis_policy_ctrl.md

https://github.com/open-cluster-management/backlog/issues/2004#issuecomment-622217011

Add the example output and validate Minio steps

---

governance/cert_policy_ctrl.md
governance/cis_policy_ctrl.md
governance/iam_policy_ctrl.md

https://github.com/open-cluster-management/backlog/issues/1983

adding link to reference user to config policy samples

---

governance/iam_policy_ctrl.md

https://github.com/open-cluster-management/backlog/issues/2027

fixing indents

---

release_notes/known_issues.md

https://github.com/open-cluster-management/backlog/issues/2010

Adding known issue etcd

---

about/architecture.md

Adding definitions for review by architects before I add them to the glossary

 open-cluster-management/backlog#1774--terms needed in arch topic

---

governance/create_policy.md
governance/policy_controllers.md
governance/policy_overview.md

https://github.com/open-cluster-management/backlog/issues/2077

Explaining remediationAction

---

apis/app_lifecycle_api_files/application.json
apis/app_lifecycle_api_files/channels.json
apis/app_lifecycle_api_files/deployables.json
apis/app_lifecycle_api_files/helmreleases.json
apis/app_lifecycle_api_files/placementrules.json
apis/app_lifecycle_api_files/subscriptions.json

Reverts open-cluster-management/rhacm-docs#525

Revert "open-cluster-management/backlog#209-- duplicates"

---

governance/cis_policy_ctrl.md

https://github.com/open-cluster-management/backlog/issues/2042

enable cis policy controller feature flag

---

governance/cis_policy_ctrl.md
manage_applications/deployment_app.md
manage_applications/managing_apps.md
manage_applications/managing_channels.md
manage_applications/managing_deployables.md
manage_applications/managing_placement_rules.md

@dockerymick I think this is a fix in one your files that got merged yesterday.

minor fix cis policy doc

---

apis/master.adoc
release_notes/master.adoc

API guide minor fixes

---

cert_manager/cert_mgmt_ingress.md
cert_manager/cert_root_ca.md

https://github.com/open-cluster-management/backlog/issues/1980

Updates for cert 

---

manage_applications/managing_placement_rules.md

Change placementRule value in the sample

open-cluster-management/backlog#2197 change pr

---

governance/config_policy_ctrl.md
governance/namespace_policy.md
governance/policy_example.md
governance/policy_sample_intro.md
release_notes/known_issues.md

made some updates for quick clean up

---

cert_manager/cert_mgmt_ingress.md
cert_manager/cert_root_ca.md

removing the anchors for certificate manager

---

release_notes/whats_new.md

small update for whats_new

---

release_notes/known_issues.md

https://github.com/open-cluster-management/backlog/issues/2074

updating the arch for known issue

---

release_notes/known_issues.md
security/cert_policy_ctrl.md

https://github.com/open-cluster-management/backlog/issues/2302
The Certificate policy file itself is still a work in progress. I will come back and address other comments after this PR is closed for the known issue

adding known issue for certificate policy

---

release_notes/known_issues.md

https://github.com/open-cluster-management/backlog/issues/2312#issuecomment-630414399

RBAC known issue

---

security/cert_mgmt_ingress.md
security/cert_root_ca.md

made a change based on personal note for cleanup

---

manage_applications/master.adoc

trying to address: section title out of sequence: expected level 1, got level 2 in manage app book

WARNING in build

---

security/create_cis_pol.md
security/create_config_pol.md
security/create_image_vuln.md
security/create_memory_policy.md
security/manage_policy_overview.md
security/master.adoc
security/memory_policy.md
summary.md

https://github.com/open-cluster-management/backlog/issues/2195

Adding task for the memory usage policy

---

release_notes/known_issues.md

https://github.com/open-cluster-management/backlog/issues/2228

starting known issue for search

---

security/policy_example.md

https://github.com/open-cluster-management/backlog/issues/2153

updating policy overview

---

security/create_cis_pol.md
security/psp_policy.md

https://github.com/open-cluster-management/backlog/issues/2004#issuecomment-623654388

Changes for CIS 

---

security/master.adoc

updating master.adoc for Security

---

install/requirements.md
manage_applications/deploying.md
manage_applications/managing_deployables.md

open-cluster-management/backlog#1573

---

security/create_cert_pol.md
security/create_config_pol.md
security/create_iam_policy.md

https://github.com/open-cluster-management/backlog/issues/1982#issuecomment-634961527

fixing spelling errors

---

about/glossary_terms.md

@dockerymick this is prob the best way to highlight and order the current terms with a unique ID and then we can close this. Please review?
In this PR, please add any of the other terms from the google doc that you are sure you want to add before the playback. Strike them out as you add so we don't repeat our efforts.
This list is what I was sure of before the release, but you may have finalized a few more. Then let's merge and close this issue as the start of the glossary effort.

open-cluster-management/backlog#1774- list identifiers

---

console/console_intro.md
manage_applications/managing_apps_console.md

no issue, making changes to fix the book in staging env.

updating links web console

---

security/create_cis_pol.md
security/create_config_pol.md
security/create_iam_policy.md
security/create_image_vuln.md
security/create_memory_policy.md
security/create_nginx_policy.md
security/create_ns_policy.md
security/create_policy.md
security/create_psp_policy.md
security/create_rb_policy.md
security/create_role_policy.md
security/create_scc_policy.md

https://github.com/open-cluster-management/backlog/issues/1982#issuecomment-634961527

adding a section to disable policies

---

manage_applications/secret_sample.md

open-cluster-management/backlog#1573 build fix

---

release_notes/known_issues.md

Book updates for Release Notes

---

release_notes/known_issues.md

Revert change for Release note book

---

console/console.md

network not part of the topology

open-cluster-management/backlog#1988

---

troubleshoot_acm/trouble_app_subscription.md

https://github.com/open-cluster-management/backlog/issues/2054
Content for the new troubleshooting file, which I will remove for 2.0

Swope app work

---

security/cert_policy_ctrl.md
security/create_cert_pol.md

Removed disabled from the cert policy doc per request: https://github.com/open-cluster-management/backlog/issues/2237#issuecomment-632239751

removed the disabled from cert policy

---

security/iam_policy_ctrl.md

https://github.com/open-cluster-management/backlog/issues/2128

Changes for IAM Policy controller 2128

---

README.md

As there will be issue with creating the normal SECURITY.md file, the text of the security policy has been added to the repo here.

Add repo security policy to README

---

install/install_connected.md

https://github.com/open-cluster-management/backlog/issues/2582

making changes for install
